name: Docker Image CI

on: [workflow_dispatch]

jobs:

  amd_job:
    name: AMD Job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Server....
      run: |
        cd Server
        ./sh

    - name: Build the Docker image for Client....
      run: |
        cd Client
        ./sh
  power_job:
    name: Power Job
    runs-on: ubuntu-20.04-ppc64le
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Server....
      run: |
        sudo chmod 666 /var/run/docker.sock
        cd Server
        ./sh

    - name: Build the Docker image for Client....
      run: |
        cd Client
        ./sh
