name: Generate Lots of Logs

on: [workflow_dispatch]

jobs:
  generate_logs:
    runs-on: ubuntu-latest-ppc64le

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Logs
        run: |
          for i in {1..1000}; do
            echo "Log entry $i"
          done
          sleep 10m
          echo "justwoke up"
          echo "feeling fresh"
        shell: bash
