name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  amd_job:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './Client/package-lock.json'
    - run: |
        cd Client
        npm ci
        npm run build --if-present
  power_job:
    name: Power Job
    runs-on: ubuntu-22.04-ppc64le

    steps:
      - name: Run commands
        run: |
          export NODE_VERSION=${NODE_VERSION:-16}
          sudo curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          sudo source "$HOME"/.bashrc
          echo "installing nodejs $NODE_VERSION"
          nvm install "$NODE_VERSION" >/dev/null
          nvm use $NODE_VERSION
          cd Client
          npm ci
          npm run build --if-present
