name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  amd_job:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './Client/package-lock.json'
    - run: |
        cd Client
        npm ci
        npm run build --if-present
  power_job:
    name: Power Job
    runs-on: ubuntu-22.04-ppc64le

    steps:
      - name: Run commands
        run: |
          apt install -y curl
          curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          nvm install 14.17.5
          node -v
          cd Client
          npm ci
          npm run build --if-present
